### PR TITLE
Footage Capture, Process Video from RTSP, Process Video from MP4

### PR DESCRIPTION
**Pull request by tendwong**
I have contributed 3 examples here to show how to 
i) record RTSP video captured some seconds ahead and write it to MP4
ii) record RTSP video captured in the present and process it (alter it) before writing it to an MP4
iii) read from an MP4 and process it (alter it) before writing it to another MP4

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Thanks for this.  Have you finished committing to it now?  I'll test ASAP, although one obvious thing I noticed is that you don't need to call Gst.deinit.

**Comment by tendwong** [comment]
Yes its done. Ok, point noted on the Gst.deinit.

**Comment by neilcsmith-net** [comment]
For various reasons I can't test these on my setup (Ubuntu LTS with GStreamer 1.8), and I'm also a little unsure of the implementation.  However, I'll merge for now, and possibly look at reviewing soon - has flagged some API changes that would be good in the core library.

Many thanks, and sorry for the delay.

**Comment by tendwong** [comment]
Hi Neil,
Thank you very much! I am using Fedora 27 with Gstreamer 1.12. My examples are mostly about processing the video and recording them as MP4. I also have an example using JNA and the Gstreamer RTSP server from the https://github.com/GStreamer/gst-rtsp-server project but I don’t know where to put it. It basically processes the video from an RTSP stream and then renders the output to another RTSP stream. As the example uses both gst1-java-core and also C functions from the Gstreamer RTSP library, I am not sure where to contribute the example. What do you say if I contribute it as an example on gst1-java-examples?

Cheers,
Tend.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Pull request merged**
