### PR TITLE
Additional example how to use the Gstreamer in Java

### PR DESCRIPTION
**Pull request by lukasEeeE**
This example provides the basic way of how to render a video from the GStreamer in a frame in JavaFX.
Since Swing get's replaced by JavaFX it is maybe interesting for others to see how this can be done.

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Thanks for the pull request.  However, I don't want to pull this into this repository for two reasons. Firstly, I don't quite share your optimism in JavaFX replacing Swing. More importantly, JavaFX isn't part of the JDK and I don't want to add a dependency on it into gst1-java-core or gst1-java-examples.

I'd be happy to set up a gst1-javafx-examples repository if you'd like to work on that yourself?

Best wishes, Neil

**Comment by Abu-Abdullah** [comment]
2 comments:
- it is not resizing with the frame changes.
- if streaming is stopped, the last image will be displayed all the time. in the swing version, there is a timer to clean the screen if no feed is available.

**Comment by lukasEeeE** [comment]
@neilcsmith-net:
If you think it is better for the future development to provide the examples in a seperate folder that's totally ok with me.
My main intention is to provide the examples at a place where an interested person has a reasonable chance to find them.
I also can add some support for the examples.

@Abu-Abdullah:
1. Right now, the pictures should fit into the window that shows the Video/Stream.
So if you mean that the size of window is not changing with the size of the frames, this behavior was intended.
If I did not get you right, let me know.
If you want to change the size of the window according to the size of the frames this is more of a JavaFX-specific problem.
If you want to do that you could either add a changeListener that reacts if the size of a frame changes or you could bind the fitWidthProperty() of the imageview to a intproperty that represents the width of the current frame.
2. The example does implement little behavior intentionaly.
In my opinion this allows an easier view on the main idea of how the wrapper works.
I think it is more important to provide this idea because it is relatively simpel to add a more complex behavior.
I'm also aware of the fact that the seperation of the classes is not very well made.
Considering this I believe that depending on your concrete application you would chose different ways to design your program anyway.

When I have a little more time I can write an example that implements a more complexe behavior like a little media player.
If you need the behavior immediatly the easiest way to go would propably be to create a timeline that runs for a time and get's repeated indefinitly.
On every run you could check if the picture in the ImageContainer has changed. If it hasn't you can close the window/print a black image or implement whatever behavior pleases you the most.
http://stackoverflow.com/questions/9966136/javafx-periodic-background-task
At least that's what i would do if i want to have a olution that works quick and dirty.
There is a better way in JavaFX for sure.

**Comment by neilcsmith-net** [comment]
@lukasEeeE yes, it's definitely not that I don't want these! Just want to ensure both core and whatever goes in this example repo can be built and run when JavaFX isn't available / installed.

I've set up another repo at gstreamer-java/gst1-javafx-examples. You should have had two Team invitations. The JavaFX Team invite will give you admin access to the new repository.

Thanks and best wishes, Neil

**Comment by neilcsmith-net** [comment]
@lukasEeeE you'll also want to be aware that the API for AppSink has just been updated!  This unfortunately breaks existing code (but before 1.0 is the time to do it!)  See the updates to SimpleVideoComponent for what needs to change - https://github.com/gstreamer-java/gst1-java-examples/commit/2f9f66052d72295714c5e603d607dc2b12aa0e06

**Pull request closed without merging**
