### PR TITLE
Add an AppSrc/AppSink example

### PR DESCRIPTION
**Pull request by krwenholz**
Mostly, this shows how to handle a non-made up data source (e.g. a file) with all of its headers and streaming fun.

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Thanks for this.  I'll test and merge ASAP.  Before I do though, one obvious issue - can you push a commit changing the name in the header from mine to yours!

**Comment by krwenholz** [comment]
Hah yeah I'll fix that later today. Let me know if there's anything else style-wise or such. This was my first stab at gstreamer and some of the AppSink/Src stuff was a little finicky.

Side note: thanks a lot for your contributions to this project. The examples and Java bindings have been invaluable.

**Comment by krwenholz** [comment]
Header fixed.

**Comment by neilcsmith-net** [comment]
Thanks for this - merged in.  Note that when 0.9.3 is released, there is a change to the API for pad::link that will require a change in this example, and possibly in other code of yours.

**Comment by krwenholz** [comment]
Ah cool. Thanks Neil. I'll keep an eye out for that change.

**Pull request merged**
